* About
This plugin uses [[https://github.com/johang/btfs][btfs]] to allow mpv to stream torrent files directly. It will automatically unmount/cleanup once the mpv instance is closed (by default).

This script will detect =magnet:= links and torrent files/urls ending in =torrent= passed to mpv by default. If the torrent file does not end in =torrent=, you can prefix the path with =btfs://=. Example mpv commands would be ~mpv "magnet:..."~ and ~mpv /path/to/file.torrent~.

Unlike using ~btfs~ directly, this script automatically handles mounting, playing, and unmounting for you.

If you were to use ~webtorrent~ instead of ~btfs~, it would handle streaming for you too. One reason you might want to use this script over calling ~webtorrent --mpv~ is that you can start mpv with a playlist of multiple magnet links or add magnet links to the playlist of an already open mpv window (e.g. using one of the scripts that allows appending a link from the clipboard to the playlist).

Another benefit is consistency of syntax (e.g. if you have a shell command or keybinding to call ~mpv <clipboard>~, you don't need to handle torrents differently). By using this script, you can also see mpv output (which is hidden when calling ~webtorrent~ directly).

Finally, this script should allow viewing any files mpv supports (including torrents of images, which I think webtorrent may not work correctly with; even if it does, mpv-webtorrent-hook could not easily support this functionality).

* Requirements
- [[https://github.com/johang/btfs][btfs]]
- on linux (or maybe similar)
- basic shell utilities (e.g. bash, sleep, mkdir, rmdir, fusermount, nohup)
- Optionally [[https://github.com/webtorrent/webtorrent-cli][webtorrent-cli]]

If webtorrent-cli is installed:
- The directory the torrent is mounted to will be named as the info hash instead of the time. This means the same torrent will always use the same directory. This could be useful if you wanted to open/close mpv several times for a torrent without having to redownload it each time (if you set the unmount setting to =false=). This also allows resuming playback at the same position regardless of the unmount setting.

* Installation Instructions
Clone this repo into the mpv scripts directory (e.g. =git clone <url> ~/.config/mpv/scripts/btfs-hook=). You must put this whole directory in the scripts directory not just the lua file.

* Comparison with MPV Webtorrent Hook
This plugin is in alternative to [[https://github.com/noctuid/mpv-webtorrent-hook][mpv-webtorrent-hook]] that was created since btfs is much easier to work with from an mpv script.

Both
- Allow using a normal mpv call to play a torrent: ~mpv <torrent identifier>~
- Correctly show video title (i.e. file name not magnet link)

Advantages of btfs-hook
- Btfs-hook can play torrents that contain a directory with multiple videos
- Btfs-hook can play non-video torrents (e.g. directory or zipfile of images); potentially useful if you use mpv as an image viewer
- Btfs allows the script to be much simpler since it is not necessary to parse any output (edge cases and problems are less likely, e.g. webtorrent script previously broke when webtorrent output changed)

Major disadvantage
- Btfs is much slower. Once the video is playing, playback seems fine, but with btfs, it takes much longer for the video to actually start playing (e.g. 5 seconds with webtorrent-cli vs. 20 for btfs).

Minor disadvantages
- It may take a few seconds in some cases for mpv to quit
- The download speed will not be shown while waiting for the video to play
- Not all webtorrent torrent identifiers are supported (i.e. info hash). Btfs only supports playing magnet links and torrent files by default. It would be possible to add support for playing =webtorrent://<info-hash>=, but this isn't really that useful, so I haven't done it.

If you want to normally use =webtorrent-hook= but be able to open torrents that contain multiple media files, you can install both plugins and set the btfs-hook =only_handle_prefixed_files= option to =yes=. Then prefix the torrent path or magnet link with =btfs://= when you want to use =btfs-hook=.

* Configuration
In =~/.config/mpv/script-opts/btfs-hook.conf=, you can change the following settings:
- =base_mount_directory= - base directory to mount torrents in (default: =/tmp/mpv-btfs=)
- =unmount= - whether to unmount the torrent directory after closing mpv (video files will be gone unless you have =--keep= in =btfs_flags=); if =no=, you will need to manually call ~btfs unmount <path>~ to unmount (default: =yes=)
- =only_handle_prefixed_file= - whether to handle all magnet links/torrents or only those prefixed with =btfs://= (default: =no=)
- =btfs_data_directory= - btfs data directory (where videos will remain if =--keep= is used); the script will run mpv's =expand-path= command on the string first so that mpv path abbreviations such as =~/= and =~~/= can be used; empty means use btfs default (default: "")
- =btfs_flags= - json array of flags to pass to btfs when mounting; should not include =--data-directory= (use the dedicated option =btfs_data_directory= instead); example: =["--keep", "--utp-only"]= (default: none)
